import { defineLocaleMessages } from '@llmnative/react';
export default defineLocaleMessages({ showcase: { promptShared: { propsDocs: { groups: { shared: 'Gemeinsam', specific: 'Spezifisch' }, items: { name: { description: 'Feldname als Formularschlussel' }, label: { description: 'Feldlabel uber dem Komponent' }, required: { description: 'Markiert die aktive Textarea als erforderlich', default: 'false' }, defaultValue: { description: 'Initiale Prompt-Metadaten: Template-Text, enabled-Flag und KI-Einstellungen (model, role, language, voice, style, temperature).', typeDetails: `{
  value?: string;
  enabled?: boolean;
  role?: string;
  language?: string;
  voice?: string;
  style?: string;
  model?: string;
  temperature?: number;
}` }, rows: { description: 'Maximale Zeilenanzahl vor dem Scrollen' }, before: { description: 'Inhalt vor dem Prompt-Block' }, after: { description: 'Inhalt nach dem Prompt-Block' }, onChange: { description: 'Benutzerdefinierter Change-Handler aus dem Form-Kontext' }, className: { description: 'CSS-Klassen fur die aktive Textarea' }, wrapperClassName: { description: 'CSS-Klassen fur den ausseren Wrapper' }, inheritWrapperClassName: { description: 'Wenn true ubernimmt das Feld wrapperClassName aus dem ubergeordneten Form-Kontext', default: 'true' }, editorMode: { description: 'Erstellt und speichert das Prompt-Template. Zeigt einen enabled-Switch zum Ein- und Ausschalten der Prompt-Metadaten.', default: '"edit"' }, runMode: { description: 'Fuhrt das gespeicherte Template gegen den aktiven Formular-Datensatz aus und schreibt das Ergebnis in dasselbe Feld zuruck.', default: '"run"' }, plainMode: { description: 'Der Plain-Fallback nutzt weiterhin run mode, aber mit defaultValue.enabled = false.', default: '"run"' }, renderAIUnavailableEdit: { description: 'Benutzerdefinierter Inline-Renderer, wenn kein KI-Provider konfiguriert ist.' }, renderAIUnavailableRun: { description: 'Benutzerdefinierter Renderer fur den Hinweis, wenn kein KI-Provider konfiguriert ist.' }, onRunPrompt: { description: 'Optionaler benutzerdefinierter Executor. Wenn gesetzt, lauft er vor dem Standard-KI-Provider. Nützlich fur Tests, Mocks oder eigene KI-Anbindung.' }, variables: { description: 'Externe Schlussel-Wert-Paare, die zur Vorschau- und Laufzeit in das Template injiziert werden. Schlussel entsprechen {placeholder}-Tokens. Sie werden mit den Formularwerten zusammengefuhrt und gewinnen bei Kollisionen.', typeDetails: 'Record<string, unknown>' }, commands: { description: 'Slash-Befehle im Run-Mode-Footer uber den /-Button. Bei Auswahl wird der Handler mit dem aktuellen Textarea-Wert aufgerufen.', typeDetails: `{
  name: string;
  description?: string;
  icon?: string;
  handler?: (currentValue: string) => string | Promise<string>;
}[]` }, attachments: { description: 'Aktiviert die Buroklammer im Footer. Angehängte Dateien erscheinen uber der Ergebnis-Textarea und werden als multimodale Eingaben an kompatible KI-Provider weitergegeben.', default: 'false' }, actions: { description: 'Eigene Icon-Buttons im Run-Mode-Footer. Ein tokenUsage-Key aktiviert das eingebaute Token-Usage-Popup nach jedem Lauf.', typeDetails: `{
  key: string;
  icon: string;
  label?: string;
  content?: ReactNode;
}[]` }, statusItems: { description: "Benannte Elemente im Statusstreifen unter dem Footer nach jedem Lauf. Eingebaute Keys: 'tokensIn', 'tokensOut', 'contextPercent', 'model', 'duration'.", typeDetails: `('tokensIn' | 'tokensOut' | 'contextPercent' | 'model' | 'duration' | { key: string; render: (stats: PromptRunStats) => ReactNode })[]` }, renderFallbackRun: { description: 'Benutzerdefinierter Renderer, wenn der Prompt-Modus deaktiviert ist (enabled=false), und ersetzt die Standard-Textarea.' }, renderFallbackPlain: { description: 'Benutzerdefinierter Renderer, wenn der Prompt-Modus deaktiviert ist.' } } }, playground: { inspector: { providerLabel: 'KI-Provider', providerDescription: 'Wahle einen Provider und fugen einen API-Schlussel ein, um das Playground direkt mit dem eingebauten KI-Registry zu verbinden. Lass den Schlussel leer, um den unavailable-Zustand zu sehen.', apiKeyPlaceholder: 'API-Schlussel fur den ausgewahlten Provider einfugen', compatibleBaseUrlPlaceholder: 'Base-URL fur den OpenAI-kompatiblen Endpoint' }, defaults: { projectName: 'projectName', customerName: 'customerName', company: 'company', summaryLabel: 'Summary', summaryPromptLabel: 'Summary prompt', aiSummaryLabel: 'AI summary', atlasConsole: 'Atlas Console', northwindRevamp: 'Northwind Revamp', shortHumanSummary: 'A short human-written summary.', conciseProjectSummary: 'Write a concise project summary for {projectName}.', followUpEmail: 'Draft a short follow-up email for {customerName} from {company}.', english: 'English', friendly: 'friendly', concise: 'concise' }, shortcuts: { summary: { label: 'summary', help: 'Zusammenfassungs-Prompt mit aktivierter Live-Ausfuhrung.' }, email: { label: 'email', help: 'Prompt fur Kunden-Follow-up.' }, plain: { label: 'plain', help: 'Gespeicherter Text ohne Prompt-Modus.' }, none: { label: 'none', help: 'Keine externen Variablen, nur der Form-Datensatz wird verwendet.' }, product: { label: 'product', help: 'Produktkontext-Variablen.' }, customer: { label: 'customer', help: 'Kundenkontext-Variablen.' } }, mockAi: { header: '[Mock AI - Sprache: {language} · Stil: {style} · Temp: {temperature}]', defaultValue: 'default' } } } } });
