import { defineLocaleMessages } from '@llmnative/react';
export default defineLocaleMessages({ showcase: { promptShared: { propsDocs: { groups: { shared: 'مشتركة', specific: 'متخصصة' }, items: { name: { description: 'اسم الحقل المستخدم كمفتاح في النموذج' }, label: { description: 'عنوان الحقل المعروض فوق المكون' }, required: { description: 'يحدد textarea النشطة كحقل مطلوب', default: 'false' }, defaultValue: { description: 'بيانات prompt الأولية: نص القالب، علامة enabled، وإعدادات الذكاء الاصطناعي (model و role و language و voice و style و temperature).', typeDetails: `{
  value?: string;
  enabled?: boolean;
  role?: string;
  language?: string;
  voice?: string;
  style?: string;
  model?: string;
  temperature?: number;
}` }, rows: { description: 'الحد الأقصى لعدد الأسطر قبل ظهور التمرير' }, before: { description: 'محتوى يعرض قبل كتلة prompt' }, after: { description: 'محتوى يعرض بعد كتلة prompt' }, onChange: { description: 'معالج تغيير مخصص يستدعى من سياق Form' }, className: { description: 'فئات CSS الممررة إلى textarea النشطة' }, wrapperClassName: { description: 'فئات CSS الممررة إلى الغلاف الخارجي' }, inheritWrapperClassName: { description: 'عند true يرث الحقل wrapperClassName من سياق Form الأب', default: 'true' }, editorMode: { description: 'يستخدم لكتابة وحفظ قالب prompt. يعرض مفتاح enabled لتفعيل أو تعطيل بيانات prompt.', default: '"edit"' }, runMode: { description: 'يشغّل القالب المخزن على سجل النموذج النشط ويعيد كتابة النتيجة في الحقل نفسه.', default: '"run"' }, plainMode: { description: 'يظل fallback العادي يستخدم run mode ولكن مع defaultValue.enabled = false.', default: '"run"' }, renderAIUnavailableEdit: { description: 'مُصيّر inline مخصص عند عدم إعداد أي موفر AI.' }, renderAIUnavailableRun: { description: 'مُصيّر مخصص لتنبيه عدم التوفر عند غياب موفر AI.' }, onRunPrompt: { description: 'منفذ مخصص اختياري. عند تمريره يعمل قبل موفر AI الافتراضي. مفيد للاختبار أو المحاكاة أو التوصيل المخصص.' }, variables: { description: 'أزواج مفتاح-قيمة خارجية تُحقن في القالب أثناء المعاينة والتشغيل. تتطابق المفاتيح مع رموز {placeholder}. تدمج مع سجل النموذج وتملك أولوية عند التعارض.', typeDetails: 'Record<string, unknown>' }, commands: { description: 'أوامر slash المعروضة عبر زر / في تذييل وضع run. عند اختيار أحدها يتم استدعاء handler بالقيمة الحالية لـ textarea.', typeDetails: `{
  name: string;
  description?: string;
  icon?: string;
  handler?: (currentValue: string) => string | Promise<string>;
}[]` }, attachments: { description: 'يفعّل زر المشبك في التذييل. تظهر الملفات المرفقة فوق textarea الناتج ويتم تمريرها كمدخلات متعددة الوسائط إلى موفري AI المتوافقين.', default: 'false' }, actions: { description: 'أزرار أيقونات مخصصة في تذييل وضع run. يقوم مفتاح tokenUsage بتفعيل نافذة تفاصيل استخدام التوكنات بعد كل تشغيل.', typeDetails: `{
  key: string;
  icon: string;
  label?: string;
  content?: ReactNode;
}[]` }, statusItems: { description: "عناصر مسماة تظهر في شريط الحالة أسفل التذييل بعد كل تشغيل. المفاتيح المدمجة: 'tokensIn' و 'tokensOut' و 'contextPercent' و 'model' و 'duration'.", typeDetails: `('tokensIn' | 'tokensOut' | 'contextPercent' | 'model' | 'duration' | { key: string; render: (stats: PromptRunStats) => ReactNode })[]` }, renderFallbackRun: { description: 'مُصيّر مخصص عند تعطيل وضع prompt (enabled=false)، ويستبدل textarea العادية الافتراضية.' }, renderFallbackPlain: { description: 'مُصيّر مخصص عند تعطيل وضع prompt.' } } }, playground: { inspector: { providerLabel: 'موفر AI', providerDescription: 'اختر موفرًا والصق API key لربط الـ playground مباشرة بسجل AI المدمج. اترك المفتاح فارغًا لرؤية حالة unavailable.', apiKeyPlaceholder: 'الصق API key للموفر المحدد', compatibleBaseUrlPlaceholder: 'Base URL لنقطة OpenAI-compatible' }, defaults: { projectName: 'projectName', customerName: 'customerName', company: 'company', summaryLabel: 'Summary', summaryPromptLabel: 'Summary prompt', aiSummaryLabel: 'AI summary', atlasConsole: 'Atlas Console', northwindRevamp: 'Northwind Revamp', shortHumanSummary: 'A short human-written summary.', conciseProjectSummary: 'Write a concise project summary for {projectName}.', followUpEmail: 'Draft a short follow-up email for {customerName} from {company}.', english: 'English', friendly: 'friendly', concise: 'concise' }, shortcuts: { summary: { label: 'summary', help: 'Prompt ملخص مع تفعيل التنفيذ المباشر.' }, email: { label: 'email', help: 'Prompt لمتابعة العميل.' }, plain: { label: 'plain', help: 'نص مخزن دون وضع prompt.' }, none: { label: 'none', help: 'لا توجد متغيرات خارجية، يستخدم فقط سجل النموذج.' }, product: { label: 'product', help: 'متغيرات سياق المنتج.' }, customer: { label: 'customer', help: 'متغيرات سياق العميل.' } }, mockAi: { header: '[Mock AI - اللغة: {language} · الأسلوب: {style} · temp: {temperature}]', defaultValue: 'default' } } } } });
