import { defineLocaleMessages } from '@llmnative/react';
export default defineLocaleMessages({ showcase: { promptShared: { propsDocs: { groups: { shared: 'Общие', specific: 'Специфичные' }, items: { name: { description: 'Имя поля, используемое как ключ формы' }, label: { description: 'Подпись поля над компонентом' }, required: { description: 'Помечает активную textarea как обязательную', default: 'false' }, defaultValue: { description: 'Начальные метаданные prompt: текст шаблона, флаг enabled и настройки AI (model, role, language, voice, style, temperature).', typeDetails: `{
  value?: string;
  enabled?: boolean;
  role?: string;
  language?: string;
  voice?: string;
  style?: string;
  model?: string;
  temperature?: number;
}` }, rows: { description: 'Максимальное число строк textarea до появления прокрутки' }, before: { description: 'Контент перед блоком prompt' }, after: { description: 'Контент после блока prompt' }, onChange: { description: 'Пользовательский обработчик изменения из контекста Form' }, className: { description: 'CSS-классы для активной textarea' }, wrapperClassName: { description: 'CSS-классы внешнего wrapper' }, inheritWrapperClassName: { description: 'Если true, поле наследует wrapperClassName из родительского контекста Form', default: 'true' }, editorMode: { description: 'Позволяет писать и сохранять шаблон prompt. Показывает Switch enabled для включения и отключения метаданных prompt.', default: '"edit"' }, runMode: { description: 'Выполняет сохраненный шаблон на активной записи формы и записывает результат обратно в то же поле.', default: '"run"' }, plainMode: { description: 'Plain fallback все равно использует run mode, но с defaultValue.enabled = false.', default: '"run"' }, renderAIUnavailableEdit: { description: 'Пользовательский inline-рендер, когда AI provider не настроен.' }, renderAIUnavailableRun: { description: 'Пользовательский рендер предупреждения, когда AI provider не настроен.' }, onRunPrompt: { description: 'Необязательный пользовательский executor. Если передан, вызывается раньше провайдера AI по умолчанию. Полезно для тестов, mock и своей AI-интеграции.' }, variables: { description: 'Внешние пары ключ-значение, подставляемые в шаблон при preview и run. Ключи соответствуют токенам {placeholder}. Объединяются с данными формы и имеют приоритет при совпадениях.', typeDetails: 'Record<string, unknown>' }, commands: { description: 'Slash-команды через кнопку / в footer режима run. При выборе вызывается handler с текущим значением textarea.', typeDetails: `{
  name: string;
  description?: string;
  icon?: string;
  handler?: (currentValue: string) => string | Promise<string>;
}[]` }, attachments: { description: 'Включает кнопку скрепки в footer. Прикрепленные файлы показываются над textarea результата и передаются как мультимодальные входы совместимым AI-провайдерам.', default: 'false' }, actions: { description: 'Пользовательские кнопки-иконки в footer режима run. Ключ tokenUsage включает встроенный popup использования токенов после каждого запуска.', typeDetails: `{
  key: string;
  icon: string;
  label?: string;
  content?: ReactNode;
}[]` }, statusItems: { description: "Именованные элементы в строке статуса под footer после каждого запуска. Встроенные ключи: 'tokensIn', 'tokensOut', 'contextPercent', 'model', 'duration'.", typeDetails: `('tokensIn' | 'tokensOut' | 'contextPercent' | 'model' | 'duration' | { key: string; render: (stats: PromptRunStats) => ReactNode })[]` }, renderFallbackRun: { description: 'Пользовательский рендер, когда режим prompt отключен (enabled=false), заменяет стандартную plain textarea.' }, renderFallbackPlain: { description: 'Пользовательский рендер, когда режим prompt отключен.' } } }, playground: { inspector: { providerLabel: 'AI provider', providerDescription: 'Выберите провайдера и вставьте API key, чтобы подключить playground к встроенному AI registry. Оставьте ключ пустым, чтобы увидеть unavailable state.', apiKeyPlaceholder: 'Вставьте API key для выбранного провайдера', compatibleBaseUrlPlaceholder: 'Base URL для OpenAI-compatible endpoint' }, defaults: { projectName: 'projectName', customerName: 'customerName', company: 'company', summaryLabel: 'Summary', summaryPromptLabel: 'Summary prompt', aiSummaryLabel: 'AI summary', atlasConsole: 'Atlas Console', northwindRevamp: 'Northwind Revamp', shortHumanSummary: 'A short human-written summary.', conciseProjectSummary: 'Write a concise project summary for {projectName}.', followUpEmail: 'Draft a short follow-up email for {customerName} from {company}.', english: 'English', friendly: 'friendly', concise: 'concise' }, shortcuts: { summary: { label: 'summary', help: 'Суммаризирующий prompt с включенным live execution.' }, email: { label: 'email', help: 'Prompt для follow-up клиенту.' }, plain: { label: 'plain', help: 'Сохраненный текст без prompt mode.' }, none: { label: 'none', help: 'Без внешних переменных, используется только запись формы.' }, product: { label: 'product', help: 'Переменные продуктового контекста.' }, customer: { label: 'customer', help: 'Переменные клиентского контекста.' } }, mockAi: { header: '[Mock AI - язык: {language} · стиль: {style} · temp: {temperature}]', defaultValue: 'default' } } } } });
