import { defineLocaleMessages } from '@llmnative/react';
export default defineLocaleMessages({ showcase: { promptShared: { propsDocs: { groups: { shared: 'Condivise', specific: 'Specifiche' }, items: { name: { description: 'Nome campo usato come chiave del form' }, label: { description: 'Etichetta mostrata sopra il componente' }, required: { description: 'Marca la textarea attiva come obbligatoria', default: 'false' }, defaultValue: { description: 'Metadati iniziali del prompt: testo template, flag enabled e impostazioni AI (model, role, language, voice, style, temperature).', typeDetails: `{
  value?: string;
  enabled?: boolean;
  role?: string;
  language?: string;
  voice?: string;
  style?: string;
  model?: string;
  temperature?: number;
}` }, rows: { description: 'Numero massimo di righe prima dello scroll' }, before: { description: 'Contenuto renderizzato prima del blocco prompt' }, after: { description: 'Contenuto renderizzato dopo il blocco prompt' }, onChange: { description: 'Handler custom di cambio chiamato dal contesto Form' }, className: { description: 'Classi CSS passate alla textarea attiva' }, wrapperClassName: { description: 'Classi CSS passate al wrapper esterno' }, inheritWrapperClassName: { description: 'Quando true il campo eredita wrapperClassName dal contesto Form padre', default: 'true' }, editorMode: { description: 'Permette di scrivere e salvare il template del prompt. Espone uno Switch enabled per attivare o disattivare i metadati prompt.', default: '"edit"' }, runMode: { description: 'Esegue il template salvato sul record attivo del form e riscrive il risultato nello stesso campo.', default: '"run"' }, plainMode: { description: 'Il fallback plain usa ancora la modalita run ma con defaultValue.enabled = false.', default: '"run"' }, renderAIUnavailableEdit: { description: 'Renderer inline personalizzato mostrato quando non e configurato alcun provider AI.' }, renderAIUnavailableRun: { description: 'Renderer personalizzato per l’avviso mostrato quando nessun provider AI e configurato.' }, onRunPrompt: { description: 'Esecutore custom opzionale. Se fornito viene chiamato prima del provider AI di default. Utile per test, mock o integrazioni custom.' }, variables: { description: 'Coppie chiave-valore esterne iniettate nel template in preview e in run. Le chiavi corrispondono ai token {placeholder}. Vengono fuse col record del form e hanno precedenza in caso di collisione.', typeDetails: 'Record<string, unknown>' }, commands: { description: 'Slash command mostrate tramite il pulsante / nel footer della modalita run. Selezionandone una viene chiamato il suo handler con il valore corrente della textarea.', typeDetails: `{
  name: string;
  description?: string;
  icon?: string;
  handler?: (currentValue: string) => string | Promise<string>;
}[]` }, attachments: { description: 'Abilita il pulsante graffetta nel footer. I file allegati appaiono sopra la textarea del risultato e vengono inoltrati come input multimodali ai provider compatibili.', default: 'false' }, actions: { description: 'Pulsanti icona personalizzati nel footer della modalita run. Una chiave tokenUsage attiva il popup integrato di utilizzo token dopo ogni esecuzione.', typeDetails: `{
  key: string;
  icon: string;
  label?: string;
  content?: ReactNode;
}[]` }, statusItems: { description: "Elementi nominali mostrati nella strip di stato sotto il footer dopo ogni run. Chiavi built-in: 'tokensIn', 'tokensOut', 'contextPercent', 'model', 'duration'.", typeDetails: `('tokensIn' | 'tokensOut' | 'contextPercent' | 'model' | 'duration' | { key: string; render: (stats: PromptRunStats) => ReactNode })[]` }, renderFallbackRun: { description: 'Renderer custom mostrato quando la modalita prompt e disabilitata (enabled=false), sostituendo la textarea plain di default.' }, renderFallbackPlain: { description: 'Renderer custom mostrato quando la modalita prompt e disabilitata.' } } }, playground: { inspector: { providerLabel: 'Provider AI', providerDescription: 'Scegli un provider e incolla una API key per collegare il playground al registro AI integrato. Lascia la chiave vuota per vedere lo stato unavailable.', apiKeyPlaceholder: 'Incolla la API key per il provider selezionato', compatibleBaseUrlPlaceholder: 'Base URL per l’endpoint OpenAI-compatible' }, defaults: { projectName: 'projectName', customerName: 'customerName', company: 'company', summaryLabel: 'Summary', summaryPromptLabel: 'Summary prompt', aiSummaryLabel: 'AI summary', atlasConsole: 'Atlas Console', northwindRevamp: 'Northwind Revamp', shortHumanSummary: 'A short human-written summary.', conciseProjectSummary: 'Write a concise project summary for {projectName}.', followUpEmail: 'Draft a short follow-up email for {customerName} from {company}.', english: 'English', friendly: 'friendly', concise: 'concise' }, shortcuts: { summary: { label: 'summary', help: 'Prompt riassuntivo con esecuzione live abilitata.' }, email: { label: 'email', help: 'Prompt per follow-up cliente.' }, plain: { label: 'plain', help: 'Testo salvato senza modalita prompt.' }, none: { label: 'none', help: 'Nessuna variabile esterna, viene usato solo il record del form.' }, product: { label: 'product', help: 'Variabili di contesto prodotto.' }, customer: { label: 'customer', help: 'Variabili di contesto cliente.' } }, mockAi: { header: '[Mock AI - lingua: {language} · stile: {style} · temp: {temperature}]', defaultValue: 'default' } } } } });
