import React from 'react';
import PageLayout from '../../components/PageLayout';

export default function DocsOverview() {
    return (
        <PageLayout
            title="Introduction"
            description="react-firestrap is a schema-driven React framework that turns field definitions into full UI + persistence with minimal code."
        >
            <div className="prose max-w-none space-y-6 text-sm text-foreground">

                <div className="card p-5">
                    <h2 className="font-semibold mb-2">What is react-firestrap?</h2>
                    <p className="text-muted-foreground">
                        A component library built on React 18 + Tailwind CSS that provides ready-made CRUD
                        widgets (Grid, Form), a provider abstraction layer for data/storage/auth/email,
                        and a composable theming system. Define your fields — get UI + persistence.
                    </p>
                </div>

                <div className="grid grid-cols-2 gap-4">
                    {[
                        { title: 'Schema-driven', desc: 'Define columns or fields once — Grid and Form render everything automatically.' },
                        { title: 'Provider pattern', desc: 'Swap Firebase for Supabase (or any custom source) by passing a different provider — zero widget changes.' },
                        { title: 'Tailwind-first', desc: 'No Bootstrap runtime. CSS is generated by Tailwind v4 — fully tree-shaken and customisable.' },
                        { title: 'TypeScript strict', desc: 'Full strict mode. DataProvider interface, RecordProps, ColumnFormatter — all typed.' },
                    ].map((f) => (
                        <div key={f.title} className="card p-4">
                            <div className="font-semibold text-foreground mb-1">{f.title}</div>
                            <div className="text-xs text-muted-foreground">{f.desc}</div>
                        </div>
                    ))}
                </div>

                <div className="card p-5">
                    <h2 className="font-semibold mb-3">Quick start</h2>
                    <pre className="text-xs bg-muted rounded p-4 overflow-x-auto leading-relaxed">{`npm install react-firestrap

// Import the stylesheet once in your entry point
import 'react-firestrap/dist/index.css';

// Minimal CRUD list — powered by Firebase Realtime DB
import { Grid } from 'react-firestrap';

export default function Users() {
    return (
        <Grid
            dataStoragePath="/users"
            columns={[
                { key: 'name',  label: 'Name',  sort: true },
                { key: 'email', label: 'Email' },
                { key: 'role',  label: 'Role' },
            ]}
            allowedActions={['add', 'edit', 'delete']}
            type="table"
        />
    );
}`}</pre>
                </div>

            </div>
        </PageLayout>
    );
}
