import React from 'react';
import PageLayout from '../../components/PageLayout';

export default function DocsOverview() {
    return (
        <PageLayout
            title="Introduction"
            description="react-firestrap is a schema-driven React framework that turns field definitions into full UI + persistence with minimal code."
        >
            <div className="prose max-w-none space-y-6 text-sm text-foreground">
                <div className="card p-5">
                    <h2 className="font-semibold mb-2">What is react-firestrap?</h2>
                    <p className="text-muted-foreground">
                        A component library built on React 18 + Tailwind CSS that provides ready-made CRUD
                        widgets (Grid, Form), a provider abstraction layer for data/storage/auth/email,
                        and a composable theming system. Define your fields and get UI plus persistence.
                    </p>
                </div>

                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                    {[
                        { title: 'Schema-driven', desc: 'Define columns or fields once. Grid and Form render everything automatically.' },
                        { title: 'Provider pattern', desc: 'Swap Firebase for Supabase or any custom source by passing a different provider.' },
                        { title: 'Tailwind-first', desc: 'No Bootstrap runtime. CSS is generated by Tailwind v4 and can be customized.' },
                        { title: 'TypeScript strict', desc: 'Strict mode, typed provider contracts, typed records and component props.' },
                    ].map((feature) => (
                        <div key={feature.title} className="card p-4">
                            <div className="font-semibold text-foreground mb-1">{feature.title}</div>
                            <div className="text-xs text-muted-foreground">{feature.desc}</div>
                        </div>
                    ))}
                </div>

                <div className="card p-5">
                    <h2 className="font-semibold mb-2">Where to go next</h2>
                    <p className="text-sm text-muted-foreground">
                        New apps should start with Quick start or Create an app. Existing apps can use Installation
                        and App configuration to wire react-firestrap into their current Vite setup.
                    </p>
                </div>
            </div>
        </PageLayout>
    );
}
