import React from 'react';
import PageLayout from '../../components/PageLayout';
import Section from '../../components/Section';

export default function Scaffolding() {
    return (
        <PageLayout
            title="Scaffolding"
            description="The official CLI generates a Vite-first react-firestrap consumer with App, menuConfig, layouts and provider configuration already wired."
        >
            <Section
                title="Create a project"
                preview={
                    <div className="grid gap-3 md:grid-cols-3">
                        {['Vite', 'App', 'VITE_* env'].map((item) => (
                            <div key={item} className="card p-4">
                                <p className="text-sm font-semibold">{item}</p>
                                <p className="text-xs text-muted-foreground mt-1">Generated by the CLI</p>
                            </div>
                        ))}
                    </div>
                }
                code={`npx react-firestrap create

# Non-interactive mode for CI/examples
npx react-firestrap create --yes --provider=mock`}
            />

            <Section
                title="Interactive prompts"
                description="Interactive mode collects the application choices before writing files, so the generated project starts with provider, theme and icon wiring already in place."
                preview={
                    <div className="grid gap-2 text-sm md:grid-cols-2">
                        {['Project name', 'Data provider', 'Icon provider', 'Theme preset', 'Provider credentials'].map((item) => (
                            <div key={item} className="rounded-md border bg-card p-3">{item}</div>
                        ))}
                    </div>
                }
                code={`npx react-firestrap create

# Prompt values
project name: my-app
data provider: firebase | supabase | mock | custom
icon provider: lucide | phosphor
theme preset: default | flat | cyber

# Firebase adds Firebase and Google OAuth prompts
# Supabase adds URL and anon key prompts`}
            />

            <Section
                title="Generated env"
                description="The scaffold writes Vite-compatible client variables. src/conf/app.ts reads these values and passes them to App from src/index.tsx."
                preview={
                    <div className="alert alert-success text-sm w-full">
                        Use VITE_* names in Vite consumers; REACT_APP_* is legacy CRA/Webpack naming.
                    </div>
                }
                code={`VITE_DATA_PROVIDER=firebase
VITE_ICON_PROVIDER=lucide
VITE_THEME_PROVIDER=default

VITE_FIREBASE_APIKEY=...
VITE_FIREBASE_AUTH_DOMAIN=...
VITE_FIREBASE_DATABASE_URL=...
VITE_FIREBASE_PROJECT_ID=...
VITE_FIREBASE_STORAGE_BUCKET=...
VITE_FIREBASE_MESSAGING_SENDER_ID=...
VITE_FIREBASE_APP_ID=...
VITE_FIREBASE_MEASUREMENT_ID=...
VITE_GOOGLE_CLIENT_ID=...

VITE_SUPABASE_URL=...
VITE_SUPABASE_ANON_KEY=...`}
            />

            <Section
                title="Generated structure"
                description="The scaffold uses familiar React boundaries: configuration, layouts, routable pages, page sections, shared components, local data and styles."
                preview={
                    <div className="alert alert-info text-sm w-full">
                        Provider implementations stay inside react-firestrap by default; the consumer configures them from App.
                    </div>
                }
                code={`my-app/
  index.html
  vite.config.ts
  package.json
  src/
    index.tsx
    conf/
      app.ts
      menu.ts
    layouts/
      AppLayout.tsx
    pages/
      home/
        HomePage.tsx
    sections/
      home/
        TasksSection.tsx
    components/
      EmptyState.tsx
      PageHeader.tsx
    data/
      mockData.ts
    styles/
      globals.css`}
            />

            <Section
                title="Folder roles"
                description="Keep provider customization optional. Most apps only need App configuration and app-local data."
                preview={
                    <div className="grid gap-2 text-sm md:grid-cols-2">
                        {['conf = wiring', 'pages = routes', 'sections = page blocks', 'components = shared UI'].map((item) => (
                            <div key={item} className="rounded-md border bg-card p-3">{item}</div>
                        ))}
                    </div>
                }
                code={`src/conf       # App wiring: menu, theme, icons, env choices
src/layouts    # Application shells and page chrome
src/pages      # Routable pages referenced by menuConfig
src/sections   # Page/feature-specific composition blocks
src/components # Shared reusable UI
src/data       # Mock data and local fixtures
src/styles     # App CSS and framework stylesheet import`}
            />

            <Section
                title="Non-interactive examples"
                description="Use flags for CI, examples, docs fixtures or repeatable scaffolding."
                preview={
                    <div className="grid gap-2 text-sm md:grid-cols-2">
                        {['mock', 'firebase', 'supabase', 'custom'].map((provider) => (
                            <div key={provider} className="rounded-md border bg-card p-3">{provider}</div>
                        ))}
                    </div>
                }
                code={`npx react-firestrap create --yes --name=my-app --provider=mock

npx react-firestrap create --yes \\
  --name=my-firebase-app \\
  --provider=firebase \\
  --icon-provider=lucide \\
  --theme-provider=default \\
  --firebase-api-key=... \\
  --firebase-auth-domain=... \\
  --firebase-database-url=... \\
  --firebase-project-id=... \\
  --firebase-storage-bucket=... \\
  --firebase-messaging-sender-id=... \\
  --firebase-app-id=... \\
  --google-client-id=...

npx react-firestrap create --yes \\
  --name=my-supabase-app \\
  --provider=supabase \\
  --supabase-url=... \\
  --supabase-anon-key=...`}
            />

            <Section
                title="Provider choices"
                description="Provider implementations are owned by react-firestrap unless the app opts into custom wiring."
                preview={
                    <div className="flex flex-wrap gap-2">
                        {['firebase', 'supabase', 'mock', 'custom'].map((provider) => (
                            <span key={provider} className="badge bg-secondary">{provider}</span>
                        ))}
                    </div>
                }
                code={`dataProvider="firebase"  # Firebase Realtime Database
dataProvider="supabase"  # Supabase
dataProvider="mock"      # In-memory data from src/data/mockData.ts
dataProvider="custom"    # Provide your own dataProvider to App

# Theme and icons are App-managed
iconProvider="lucide"
themeProvider="default"`}
            />
        </PageLayout>
    );
}
