import React from 'react';
import PageLayout from '../../components/PageLayout';
import Section from '../../components/Section';

export default function Scaffolding() {
    return (
        <PageLayout
            title="Scaffolding"
            description="The official CLI generates a Vite-first react-firestrap consumer with App, menuConfig, layouts and provider configuration already wired."
        >
            <Section
                title="Create a project"
                preview={
                    <div className="grid gap-3 md:grid-cols-3">
                        {['Vite', 'App', 'menuConfig'].map((item) => (
                            <div key={item} className="card p-4">
                                <p className="text-sm font-semibold">{item}</p>
                                <p className="text-xs text-muted-foreground mt-1">Generated by the CLI</p>
                            </div>
                        ))}
                    </div>
                }
                code={`npx react-firestrap create

# Non-interactive mode for CI/examples
npx react-firestrap create --yes --provider=mock`}
            />

            <Section
                title="Generated structure"
                description="The scaffold uses familiar React boundaries: configuration, layouts, routable pages, page sections, shared components, local data and styles."
                preview={
                    <div className="alert alert-info text-sm w-full">
                        Provider implementations stay inside react-firestrap by default; the consumer configures them from App.
                    </div>
                }
                code={`my-app/
  index.html
  vite.config.ts
  package.json
  src/
    index.tsx
    conf/
      app.ts
      menu.ts
    layouts/
      AppLayout.tsx
    pages/
      home/
        HomePage.tsx
    sections/
      home/
        TasksSection.tsx
    components/
      EmptyState.tsx
      PageHeader.tsx
    data/
      mockData.ts
    styles/
      globals.css`}
            />

            <Section
                title="Folder roles"
                description="Keep provider customization optional. Most apps only need App configuration and app-local data."
                preview={
                    <div className="grid gap-2 text-sm md:grid-cols-2">
                        {['conf = wiring', 'pages = routes', 'sections = page blocks', 'components = shared UI'].map((item) => (
                            <div key={item} className="rounded-md border bg-card p-3">{item}</div>
                        ))}
                    </div>
                }
                code={`src/conf       # App wiring: menu, theme, icons, env choices
src/layouts    # Application shells and page chrome
src/pages      # Routable pages referenced by menuConfig
src/sections   # Page/feature-specific composition blocks
src/components # Shared reusable UI
src/data       # Mock data and local fixtures
src/styles     # App CSS and framework stylesheet import`}
            />

            <Section
                title="Provider choices"
                description="The CLI can prepare Firebase, Supabase, mock or custom provider wiring."
                preview={
                    <div className="flex flex-wrap gap-2">
                        {['firebase', 'supabase', 'mock', 'custom'].map((provider) => (
                            <span key={provider} className="badge bg-secondary">{provider}</span>
                        ))}
                    </div>
                }
                code={`# Available provider prompt values
firebase
supabase
mock
custom

# Theme and icons are App-managed
iconProvider="lucide"
themeProvider="default"`}
            />
        </PageLayout>
    );
}
