import React from 'react';
import PageLayout from '../../components/PageLayout';
import Section from '../../components/Section';

export default function Scaffolding() {
    return (
        <PageLayout
            title="Scaffolding"
            description="The official CLI generates a Vite-first react-firestrap consumer with App, menuConfig, layout and provider configuration already wired."
        >
            <Section
                title="Create a project"
                preview={
                    <div className="grid gap-3 md:grid-cols-3">
                        {['Vite', 'App', 'menuConfig'].map((item) => (
                            <div key={item} className="card p-4">
                                <p className="text-sm font-semibold">{item}</p>
                                <p className="text-xs text-muted-foreground mt-1">Generated by the CLI</p>
                            </div>
                        ))}
                    </div>
                }
                code={`npx react-firestrap create

# Non-interactive mode for CI/examples
npx react-firestrap create --yes --provider=mock`}
            />

            <Section
                title="Generated structure"
                description="The showcase mirrors this structure so it can validate the scaffold while acting as documentation."
                preview={
                    <div className="alert alert-info text-sm w-full">
                        The generated app uses the same entry, menu and layout boundaries as this showcase.
                    </div>
                }
                code={`my-app/
  index.html
  vite.config.ts
  package.json
  src/
    index.tsx
    globals.css
    conf/
      menu.ts
    layout/
      AppLayout.tsx
    pages/
      Home.tsx`}
            />

            <Section
                title="Provider choices"
                description="The CLI can prepare Firebase, Supabase, mock or custom provider wiring."
                preview={
                    <div className="flex flex-wrap gap-2">
                        {['firebase', 'supabase', 'mock', 'custom'].map((provider) => (
                            <span key={provider} className="badge bg-secondary">{provider}</span>
                        ))}
                    </div>
                }
                code={`# Available provider prompt values
firebase
supabase
mock
custom

# Theme and icons are App-managed
iconProvider="lucide"
themeProvider="default"`}
            />
        </PageLayout>
    );
}
