import type { Theme, ThemeDefinition, ThemePresetConfig } from '../src/Theme';
import type { MotionRegistry } from '../src/motion';

export const preset: ThemePresetConfig = {
    mode: 'dark' as const,
    radius: 0,
    colors: {
        background:           '0 0% 98%',
        foreground:           '215 25% 16%',
        card:                 '0 0% 100%',
        cardForeground:       '215 25% 16%',
        popover:              '0 0% 100%',
        popoverForeground:    '215 25% 16%',
        primary:              '160 84% 39%',
        primaryForeground:    '0 0% 0%',
        secondary:            '160 20% 92%',
        secondaryForeground:  '160 25% 20%',
        muted:                '160 15% 93%',
        mutedForeground:      '215 15% 50%',
        accent:               '160 30% 90%',
        accentForeground:     '160 84% 25%',
        destructive:          '0 72% 51%',
        destructiveForeground:'0 0% 100%',
        success:              '160 84% 39%',
        successForeground:    '0 0% 0%',
        warning:              '45 96% 48%',
        warningForeground:    '0 0% 0%',
        info:                 '199 89% 48%',
        infoForeground:       '0 0% 0%',
        border:               '160 20% 85%',
        input:                '160 20% 85%',
        ring:                 '160 84% 39%',
    },
    dark: {
        background:           '220 20% 7%',
        foreground:           '160 10% 90%',
        card:                 '220 20% 10%',
        cardForeground:       '160 10% 90%',
        popover:              '220 20% 10%',
        popoverForeground:    '160 10% 90%',
        primary:              '160 84% 39%',
        primaryForeground:    '0 0% 0%',
        secondary:            '220 20% 15%',
        secondaryForeground:  '160 10% 75%',
        muted:                '220 20% 14%',
        mutedForeground:      '220 10% 55%',
        accent:               '160 60% 15%',
        accentForeground:     '160 84% 70%',
        destructive:          '0 72% 51%',
        destructiveForeground:'0 0% 100%',
        success:              '160 84% 45%',
        successForeground:    '0 0% 0%',
        warning:              '45 96% 55%',
        warningForeground:    '0 0% 0%',
        info:                 '199 89% 55%',
        infoForeground:       '0 0% 0%',
        border:               '220 20% 18%',
        input:                '220 20% 18%',
        ring:                 '160 84% 39%',
    },
};

export const motion: MotionRegistry = {
    none: {
        from: {},
        to: {},
        transition: { duration: 0, easing: 'linear', properties: ['opacity', 'transform', 'box-shadow'] },
        reducedMotion: 'always',
    },
    fade: {
        from: { opacity: 0 },
        to: { opacity: 1 },
        transition: { duration: 180, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity'] },
        reducedMotion: 'respect-user',
    },
    fadeUp: {
        from: { opacity: 0, transform: 'translateY(10px)' },
        to: { opacity: 1, transform: 'translateY(0)' },
        transition: { duration: 200, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform'] },
        reducedMotion: 'respect-user',
    },
    fadeDown: {
        from: { opacity: 0, transform: 'translateY(-10px)' },
        to: { opacity: 1, transform: 'translateY(0)' },
        transition: { duration: 180, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform', 'visibility'] },
        reducedMotion: 'respect-user',
    },
    slideFromRight: {
        from: { opacity: 0, transform: 'translateX(100%)' },
        to: { opacity: 1, transform: 'translateX(0)' },
        transition: { duration: 220, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform'] },
        reducedMotion: 'respect-user',
    },
    slideFromLeft: {
        from: { opacity: 0, transform: 'translateX(-100%)' },
        to: { opacity: 1, transform: 'translateX(0)' },
        transition: { duration: 220, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform'] },
        reducedMotion: 'respect-user',
    },
    slideFromTop: {
        from: { opacity: 0, transform: 'translateY(-100%)' },
        to: { opacity: 1, transform: 'translateY(0)' },
        transition: { duration: 220, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform'] },
        reducedMotion: 'respect-user',
    },
    slideFromBottom: {
        from: { opacity: 0, transform: 'translateY(100%)' },
        to: { opacity: 1, transform: 'translateY(0)' },
        transition: { duration: 220, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['opacity', 'transform'] },
        reducedMotion: 'respect-user',
    },
    press: {
        from: {},
        to: { transform: 'scale(0.97)' },
        transition: { duration: 110, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['transform', 'box-shadow'] },
        reducedMotion: 'respect-user',
    },
    imageZoom: {
        from: { transform: 'scale(1)' },
        to: { transform: 'scale(1.06)' },
        transition: { duration: 280, easing: 'cubic-bezier(0.16, 1, 0.3, 1)', properties: ['transform'] },
        reducedMotion: 'respect-user',
    },
};

export const components: Theme = {
    Grid: {
        Card: {
            wrapClass: '',
            className: '',
            headerClass: 'flex justify-between',
            bodyClass: 'p-0',
            footerClass: '',
            showArrow: false,
            showLoader: false,
        },
        Table: {
            wrapClass: '',
            className: 'table-striped',
            headerClass: '',
            bodyClass: '',
            footerClass: '',
            scrollClass: 'fixed-table-container',
            selectedClass: 'table-info',
        },
        Gallery: {
            wrapClass: '',
            className: '',
            scrollClass: '',
            headerClass: '',
            bodyClass: '',
            footerClass: '',
            selectedClass: 'bg-primary/20',
            gutterSize: 1,
            rowCols: 4,
        },
        Modal: {
            mode: 'form',
            size: 'lg',
            position: 'center',
            wrapClass: '',
            className: '',
            headerClass: '',
            titleClass: '',
            subTitleClass: 'pr-1 text-muted-foreground',
            bodyClass: '',
            footerClass: '',
            iconExpand: 'fullscreen',
            iconCollapse: 'fullscreen-exit',
            motion: {
                center: 'fade',
                top: 'slideFromTop',
                left: 'slideFromLeft',
                right: 'slideFromRight',
                bottom: 'slideFromBottom',
                backdrop: 'fade',
            },
        },
        i18n: {
            headerAdd: 'Aggiungi',
            headerEdit: 'Modifica',
            buttonAdd: 'Aggiungi',
        },
    },
    Table: {
        wrapClass: 'bootstrap-table',
        className: 'table-striped',
        headerClass: '',
        bodyClass: '',
        footerClass: '',
        scrollClass: 'fixed-table-container',
        selectedClass: 'table-info',
    },
    Gallery: {
        wrapClass: '',
        className: '',
        scrollClass: '',
        headerClass: '',
        bodyClass: '',
        footerClass: '',
        selectedClass: 'bg-primary/20',
        gutterSize: 4,
        rowCols: 2,
    },
    Pagination: {
        wrapClass: '',
        className: '',
        stickyClass: 'fixed-bottom mx-5',
        scrollToTop: false,
        scrollBehavior: 'auto',
        maxItems: 5,
        sticky: true,
        align: 'end',
    },
    Carousel: {
        showIndicators: true,
        showControls: true,
        showCaption: true,
        layoutDark: false,
        autoPlay: true,
    },
    Card: {
        wrapClass: '',
        className: '',
        headerClass: 'flex justify-between bg-white/[.15] font-normal',
        bodyClass: 'flex flex-col',
        footerClass: '',
        showLoader: false,
        showArrow: false,
    },
    Loader: {
        wrapClass: '',
        className: '',
        icon: 'custom-loader',
        title: 'Loading..',
        description: '',
    },
    ActionButton: {
        className: 'btn-primary',
        badgeClass: 'rounded-full bg-destructive text-destructive-foreground',
        motion: {
            press: 'press',
        },
    },
    LoadingButton: {
        className: 'btn-primary',
        badgeClass: 'rounded-full bg-destructive text-destructive-foreground',
        motion: {
            press: 'press',
        },
    },
    LinkButton: {
        className: 'btn-outline-secondary',
    },
    Alert: {
        className: '',
    },
    Badge: {
        className: '',
    },
    Modal: {
        size: 'lg',
        position: 'center',
        wrapClass: '',
        className: '',
        headerClass: '',
        titleClass: '',
        subTitleClass: 'pr-1 text-muted-foreground',
        bodyClass: '',
        footerClass: '',
        iconExpand: 'fullscreen',
        iconCollapse: 'fullscreen-exit',
        motion: {
            center: 'fade',
            top: 'slideFromTop',
            left: 'slideFromLeft',
            right: 'slideFromRight',
            bottom: 'slideFromBottom',
            backdrop: 'fade',
        },
    },
    Dropdown: {
        wrapClass: '',
        className: '',
        buttonClass: 'btn btn-outline-primary',
        badgeClass: '',
        menuClass: '',
        menuHeaderClass: '',
        menuItemClass: '',
        menuDividerClass: '',
        headerClass: '',
        footerClass: '',
        Menu: {
            wrapClass: '',
            className: 'list-none p-0 m-0',
            headerClass: '',
            itemClass: '',
            linkClass: 'flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent',
            iconClass: 'text-muted-foreground',
            textClass: '',
            badgeClass: '',
            arrowClass: '',
            submenuClass: '',
        },
        motion: {
            open: 'fadeDown',
            close: 'fadeDown',
            press: 'press',
        },
    },
    Notifications: {
        wrapClass: 'menu-item',
        Dropdown: {
            className: '',
            buttonClass: 'btn btn-link',
            menuClass: 'mt-1 fs-11px w-300px pt-1',
        },
    },
    Select: {
        wrapClass: '',
        className: '',
    },
    Autocomplete: {
        wrapClass: '',
        className: '',
    },
    Form: {
        wrapClass: '',
        buttonSaveClass: 'btn-outline-primary',
        buttonDeleteClass: 'btn-outline-danger',
        buttonBackClass: 'btn-link',
        Card: {
            headerClass: '',
            bodyClass: '',
            footerClass: 'text-right',
        },
        i18n: {
            headerAdd: 'Aggiungi',
            headerEdit: 'Modifica',
            headerNewRecord: 'Nuovo Record',
            buttonSave: 'Salva',
            buttonDelete: 'Elimina',
            buttonBack: 'Indietro',
            noticeRequiredFields: 'Per favore, compila tutti i campi obbligatori',
        },
    },
    Menu: {
        wrapClass: 'flex-1 overflow-auto p-4',
        className: 'navbar-nav flex-col mb-auto',
        headerClass: '',
        itemClass: 'nav-item',
        linkClass: 'nav-link',
        iconClass: 'mr-1',
        textClass: 'flex-grow-1',
        badgeClass: 'ml-1',
        arrowClass: '',
        submenuClass: 'nav flex-col ml-4',
    },
    Brand: {
        wrapClass: '',
        className: 'brand',
        logoClass: 'navbar-brand',
        labelClass: 'navbar-text',
    },
    SignIn: {
        className: 'flex items-center',
        avatarClass: 'avatar rounded-full mx-2',
    },
    Image: {
        wrapClass: '',
        className: '',
        motion: {
            enter: 'fade',
            hover: 'imageZoom',
        },
    },
    ImageAvatar: {
        wrapClass: '',
        className: '',
    },
    Percentage: {
        wrapClass: '',
        className: '',
    },
    Tab: {
        wrapClass: '',
        className: '',
        motion: {
            enter: 'fadeUp',
        },
    },
    Code: {
        wrapClass: '',
        className: '',
    },
    Prompt: {
        wrapClass: '',
        className: '',
    },
};

const definition: ThemeDefinition = { preset, motion, components };

export default definition;
